config { 
    type: "view",
    description:"Kopie von GA4",
    columns:{
        event_timestamp: "Microseconds Timestamp",
        user_pseudo_id: "User ID"
    },
     assertions: {
        uniqueKey: ["event_timestamp"],
        nonNull: ["user_pseudo_id"],
        rowConditions: [
            'ecommerce.purchase_revenue > 0'
        ]
  }
}

-- Use the ref() function to manage dependencies.
-- Learn more about ref() and other built in functions here: https://cloud.google.com/dataform/docs/dataform-core

SELECT * from ${ref("events_*")}
